/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.300.0
  
 File: ECCSALESDATA_SRVService.h
 Abstract: The generated proxy classes for the ECCSALESDATA_SRV Service. Service Version: 1.   
*/

#import <Foundation/Foundation.h>
#import "BaseEntityType.h"
#import "BaseComplexType.h"
#import "BaseServiceObject.h"

#pragma mark - Complex Types

@class GeoCode;
@class Address;
@class Phone;
@class URI;
@class DocumentStatus;

#pragma mark GeoCode
@interface GeoCode : BaseComplexType {
	NSNumber *m_Longitude;
	NSNumber *m_Latitude;
}

@property (strong, nonatomic) NSNumber *Longitude; ///< Longitude (geo-lon) - Edm.Double
@property (strong, nonatomic) NSNumber *Latitude; ///< Latitude (geo-lat) - Edm.Double

/**
 Static method that loads all of the complex type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param sdmProperties Dictionary containing all of the complex type properties.
*/
+ (void)loadLabels:(NSMutableDictionary *)sdmProperties;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;

@end


#pragma mark Address
@interface Address : BaseComplexType {
	NSString *m_Street;
	NSString *m_HouseNumber;
	NSString *m_HouseNumberSupplement;
	NSString *m_PostalCode;
	NSString *m_City;
	NSString *m_Region;
	NSString *m_Country;
	NSString *m_RegionCodeISO;
	NSString *m_CountryCodeISO;
	GeoCode *m_GeoCode;
}

@property (strong, nonatomic) NSString *Street; ///< Street (street) - Edm.String
@property (strong, nonatomic) NSString *HouseNumber; ///< HouseNumber - Edm.String

@property (strong, nonatomic) NSString *HouseNumberSupplement; ///< HouseNumberSupplement - Edm.String

@property (strong, nonatomic) NSString *PostalCode; ///< PostalCode (zip) - Edm.String
@property (strong, nonatomic) NSString *City; ///< City (city) - Edm.String
@property (strong, nonatomic) NSString *Region; ///< Region - Edm.String

@property (strong, nonatomic) NSString *Country; ///< Country - Edm.String

@property (strong, nonatomic) NSString *RegionCodeISO; ///< RegionCodeISO (region) - Edm.String
@property (strong, nonatomic) NSString *CountryCodeISO; ///< CountryCodeISO (country) - Edm.String
@property (strong, nonatomic) GeoCode *GeoCode; ///< GeoCode 


/**
 Static method that loads all of the complex type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param sdmProperties Dictionary containing all of the complex type properties.
*/
+ (void)loadLabels:(NSMutableDictionary *)sdmProperties;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;

@end


#pragma mark Phone
@interface Phone : BaseComplexType {
	NSString *m_PhoneType;
	NSString *m_InternationalDailingCode;
	NSString *m_PhoneNumber;
	NSString *m_PhoneExtension;
	NSString *m_Default;
	NSString *m_Comment;
}

@property (strong, nonatomic) NSString *PhoneType; ///< PhoneType - Edm.String

@property (strong, nonatomic) NSString *InternationalDailingCode; ///< Country - Edm.String

@property (strong, nonatomic) NSString *PhoneNumber; ///< Telephone - Edm.String

@property (strong, nonatomic) NSString *PhoneExtension; ///< Extension - Edm.String

@property (strong, nonatomic) NSString *Default; ///< Standard No. - Edm.String

@property (strong, nonatomic) NSString *Comment; ///< Notes - Edm.String


/**
 Static method that loads all of the complex type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param sdmProperties Dictionary containing all of the complex type properties.
*/
+ (void)loadLabels:(NSMutableDictionary *)sdmProperties;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;

@end


#pragma mark URI
@interface URI : BaseComplexType {
	NSString *m_URIType;
	NSString *m_URL;
	NSString *m_LongURL;
	NSNumber *m_Default;
	NSString *m_Comment;
}

@property (strong, nonatomic) NSString *URIType; ///< URI type - Edm.String

@property (strong, nonatomic) NSString *URL; ///< URI - Edm.String

@property (strong, nonatomic) NSString *LongURL; ///< URI - Edm.String

@property (strong, nonatomic) NSNumber *Default; ///< Default - Edm.Boolean

@property (strong, nonatomic) NSString *Comment; ///< Comment - Edm.String


/**
 Static method that loads all of the complex type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param sdmProperties Dictionary containing all of the complex type properties.
*/
+ (void)loadLabels:(NSMutableDictionary *)sdmProperties;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;

@end


#pragma mark DocumentStatus
@interface DocumentStatus : BaseComplexType {
	NSString *m_Delivery_Status;
	NSString *m_Invoice_Status;
	NSString *m_Overall_Status;
}

@property (strong, nonatomic) NSString *Delivery_Status; ///< Delivery_Status - Edm.String

@property (strong, nonatomic) NSString *Invoice_Status; ///< Invoice_Status - Edm.String

@property (strong, nonatomic) NSString *Overall_Status; ///< Overall_Status - Edm.String


/**
 Static method that loads all of the complex type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param sdmProperties Dictionary containing all of the complex type properties.
*/
+ (void)loadLabels:(NSMutableDictionary *)sdmProperties;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;

@end



#pragma mark - Entity Types

/**
 Each of the following classes represents an entity-type of the ECCSALESDATA_SRVService service.
 
 Any entity-type class should be used as following:
 
 1. The entity object may represent an existing entry of an appropriate service collection,
 if the object is initialized using data returned from an appropriate service call.
 This may be achieved by using the initWithSDMEntry: constructor,
 or using the static methods creating the entity object (parse<entity-type-name>EntriesWithData,
 parse<entity-type-name>EntryWithData, and create<entity-type-name>EntriesForSDMEntries).
 
 For retrieving the entry data, use the appropriate query properties and methods of this class 
 and of the ECCSALESDATA_SRVService class, and then execute the request (see the SDMConnectivityHelper class).
 
 2. Another option is to use this entity object as a new entry to create in an appropriate service collection.
 In this case, use the init constructor and set the appropriate properties. 
 Note that some features (as navigation properties) are not available in this mode (since it is not yet an actual service entry).
 Use the SDMConnectivityHelper class and the getXMLForCreateRequest method of the BaseServiceObject class, to send the 'create' request.
 Then use the service response for constructing a new object, in order to represent the entry as existed in the service. 
 
 In both operation modes, setting the entity property values will not affect the service until the changes are sent to the server.
 For sending changes to the server, see the SDMConnectivityHelper class and the getXMLForRequest methods of the BaseServiceObject class.
 It is recommended to use the server response for constructing a new object, in order to represent the entry as existed in the service.
 
 Note: For proper behavior of this class, make sure to initialize the ECCSALESDATA_SRVService class
 in your application, before initializing the entity-type class objects.
*/
 

#pragma mark - ContactPerson
@interface ContactPerson : BaseEntityType {
	URI *m_Website;
	URI *m_Email;
	Phone *m_FaxNumber;
	Phone *m_PhoneNumber;
	Address *m_Address;
	NSString *m_Gender;
	NSString *m_RelatedPartnerID;
	NSString *m_LastName;
	NSString *m_FirstName;
	NSString *m_ContactPersonID;
	NSString *m_FullName;
    ODataQuery *m_MediaCollectionQuery;
	NSMutableArray *m_MediaCollection;

}

@property (strong, nonatomic) URI *Website; ///< Website 
@property (strong, nonatomic) URI *Email; ///< Email 
@property (strong, nonatomic) Phone *FaxNumber; ///< FaxNumber 
@property (strong, nonatomic) Phone *PhoneNumber; ///< PhoneNumber 
@property (strong, nonatomic) Address *Address; ///< Address 
@property (strong, nonatomic) NSString *Gender; ///< Gender - Edm.String
@property (strong, nonatomic) NSString *RelatedPartnerID; ///< RelatedPartnerID - Edm.String
@property (strong, nonatomic) NSString *LastName; ///< LastName - Edm.String
@property (strong, nonatomic) NSString *FirstName; ///< FirstName - Edm.String
@property (strong, nonatomic) NSString *ContactPersonID; ///< ContactPersonID - Edm.String
@property (strong, nonatomic) NSString *FullName; ///< FullName - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *MediaCollectionQuery;
@property (strong, nonatomic) NSMutableArray *MediaCollection;

#pragma mark Static Methods
/**
 Static method that returns an array of ContactPerson entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to ContactPerson entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of ContactPerson entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseContactPersonEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of ContactPerson entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to ContactPerson entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of ContactPerson entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedContactPersonEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single ContactPerson entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a ContactPerson entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a ContactPerson entity. Returns nil if the data in invalid.
*/
+ (ContactPerson *)parseContactPersonEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single ContactPerson entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a ContactPerson entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a ContactPerson entity. Returns nil if the data in invalid.
*/
+ (ContactPerson *)parseExpandedContactPersonEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of ContactPerson objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of ContactPerson objects.
*/
+ (NSMutableArray *)createContactPersonEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads MediaCollection details for this entity from the provided data.
 @param aData The NSData containing the MediaCollection information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadMediaCollectionWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - BusinessPartner
@interface BusinessPartner : BaseEntityType {
	URI *m_Website;
	URI *m_Email;
	Phone *m_FaxNumber;
	Phone *m_PhoneNumber;
	Address *m_Address;
	NSString *m_BusinessPartnerName;
	NSString *m_BusinessPartnerType;
	NSString *m_BusinessPartnerID;
    ODataQuery *m_ContactPersonsQuery;
	NSMutableArray *m_ContactPersons;
    ODataQuery *m_MediaCollectionQuery;
	NSMutableArray *m_MediaCollection;

}

@property (strong, nonatomic) URI *Website; ///< Website 
@property (strong, nonatomic) URI *Email; ///< Email 
@property (strong, nonatomic) Phone *FaxNumber; ///< FaxNumber 
@property (strong, nonatomic) Phone *PhoneNumber; ///< PhoneNumber 
@property (strong, nonatomic) Address *Address; ///< Address 
@property (strong, nonatomic) NSString *BusinessPartnerName; ///< BusinessPartnerName - Edm.String
@property (strong, nonatomic) NSString *BusinessPartnerType; ///< BusinessPartnerType - Edm.String
@property (strong, nonatomic) NSString *BusinessPartnerID; ///< BusinessPartnerID - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *ContactPersonsQuery;
@property (strong, nonatomic) NSMutableArray *ContactPersons;
@property (strong, nonatomic) ODataQuery *MediaCollectionQuery;
@property (strong, nonatomic) NSMutableArray *MediaCollection;

#pragma mark Static Methods
/**
 Static method that returns an array of BusinessPartner entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to BusinessPartner entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of BusinessPartner entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseBusinessPartnerEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of BusinessPartner entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to BusinessPartner entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of BusinessPartner entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedBusinessPartnerEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single BusinessPartner entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a BusinessPartner entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a BusinessPartner entity. Returns nil if the data in invalid.
*/
+ (BusinessPartner *)parseBusinessPartnerEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single BusinessPartner entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a BusinessPartner entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a BusinessPartner entity. Returns nil if the data in invalid.
*/
+ (BusinessPartner *)parseExpandedBusinessPartnerEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of BusinessPartner objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of BusinessPartner objects.
*/
+ (NSMutableArray *)createBusinessPartnerEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads ContactPersons details for this entity from the provided data.
 @param aData The NSData containing the ContactPersons information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadContactPersonsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Navigation property. Loads MediaCollection details for this entity from the provided data.
 @param aData The NSData containing the MediaCollection information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadMediaCollectionWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - Material
@interface Material : BaseEntityType {
	NSNumber *m_Quantity; 
	NSString *m_UoM;
	NSString *m_Plant;
	NSString *m_Description;
	NSString *m_MaterialNumber;
	NSString *m_EANCategory;
	NSString *m_EANCode;
	NSString *m_SalesOrganization;
	NSString *m_MaterialGroup;
    ODataQuery *m_MediaCollectionQuery;
	NSMutableArray *m_MediaCollection;

}

@property (strong, nonatomic) NSNumber *Quantity; ///< Int2 - Edm.Int16
@property (strong, nonatomic) NSString *UoM; ///< UoM - Edm.String
@property (strong, nonatomic) NSString *Plant; ///< Plant - Edm.String
@property (strong, nonatomic) NSString *Description; ///< Description - Edm.String
@property (strong, nonatomic) NSString *MaterialNumber; ///< MaterialNumber - Edm.String
@property (strong, nonatomic) NSString *EANCategory; ///< EANCategory - Edm.String
@property (strong, nonatomic) NSString *EANCode; ///< EANCode - Edm.String
@property (strong, nonatomic) NSString *SalesOrganization; ///< SalesOrganization - Edm.String
@property (strong, nonatomic) NSString *MaterialGroup; ///< MaterialGroup - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *MediaCollectionQuery;
@property (strong, nonatomic) NSMutableArray *MediaCollection;

#pragma mark Static Methods
/**
 Static method that returns an array of Material entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to Material entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of Material entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseMaterialEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of Material entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to Material entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of Material entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedMaterialEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single Material entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a Material entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a Material entity. Returns nil if the data in invalid.
*/
+ (Material *)parseMaterialEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single Material entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a Material entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a Material entity. Returns nil if the data in invalid.
*/
+ (Material *)parseExpandedMaterialEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of Material objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of Material objects.
*/
+ (NSMutableArray *)createMaterialEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads MediaCollection details for this entity from the provided data.
 @param aData The NSData containing the MediaCollection information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadMediaCollectionWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - SalesDocument

@interface SalesDocument : BaseEntityType {
	DocumentStatus *m_Status;
	NSString *m_CustomerPurchaseOrderNumber;
	NSDate *m_RequestedDeliveryDate;
	NSString *m_Currency;
	NSDecimalNumber *m_NetValue;
	NSString *m_Division;
	NSString *m_DistributionChannel;
	NSString *m_SalesOrganization;
	NSString *m_CustomerID;
	NSDate *m_DocumentDate;
	NSString *m_Description;
	NSString *m_OrderType;
	NSString *m_OrderID;
    ODataQuery *m_ItemsQuery;
	NSMutableArray *m_Items;

}

@property (strong, nonatomic) DocumentStatus *Status; ///< Status 
@property (strong, nonatomic) NSString *CustomerPurchaseOrderNumber; ///< CustomerPurchaseOrderNumber - Edm.String
@property (strong, nonatomic) NSDate *RequestedDeliveryDate; ///< RequestedDeliveryDate - Edm.DateTime
@property (strong, nonatomic) NSString *Currency; ///< Currency - Edm.String
@property (strong, nonatomic) NSDecimalNumber *NetValue; ///< NetValue - Edm.Decimal
@property (strong, nonatomic) NSString *Division; ///< Division - Edm.String
@property (strong, nonatomic) NSString *DistributionChannel; ///< DistributionChannel - Edm.String
@property (strong, nonatomic) NSString *SalesOrganization; ///< SalesOrganization - Edm.String
@property (strong, nonatomic) NSString *CustomerID; ///< CustomerID - Edm.String
@property (strong, nonatomic) NSDate *DocumentDate; ///< DocumentDate - Edm.DateTime
@property (strong, nonatomic) NSString *Description; ///< Description - Edm.String
@property (strong, nonatomic) NSString *OrderType; ///< OrderType - Edm.String
@property (strong, nonatomic) NSString *OrderID; ///< OrderID - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *ItemsQuery;
@property (strong, nonatomic) NSMutableArray *Items;

#pragma mark Static Methods
/**
 Static method that returns an array of SalesDocument entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to SalesDocument entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of SalesDocument entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseSalesDocumentEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of SalesDocument entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to SalesDocument entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of SalesDocument entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedSalesDocumentEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single SalesDocument entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a SalesDocument entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a SalesDocument entity. Returns nil if the data in invalid.
*/
+ (SalesDocument *)parseSalesDocumentEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single SalesDocument entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a SalesDocument entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a SalesDocument entity. Returns nil if the data in invalid.
*/
+ (SalesDocument *)parseExpandedSalesDocumentEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of SalesDocument objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of SalesDocument objects.
*/
+ (NSMutableArray *)createSalesDocumentEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads Items details for this entity from the provided data.
 @param aData The NSData containing the Items information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadItemsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - SalesDocumentItem
@interface SalesDocumentItem : BaseEntityType {
	DocumentStatus *m_Status;
	NSDecimalNumber *m_NetValue;
	NSDecimalNumber *m_NetPrice;
	NSString *m_UoM;
	NSNumber *m_Quantity;
	NSString *m_Plant;
	NSString *m_Description;
	NSString *m_Material;
	NSString *m_ItemNumber;
	NSString *m_OrderID;
    ODataQuery *m_SalesDocumentQuery;
	NSMutableArray *m_SalesDocument;

}

@property (strong, nonatomic) DocumentStatus *Status; ///< Status 
@property (strong, nonatomic) NSDecimalNumber *NetValue; ///< NetValue - Edm.Decimal
@property (strong, nonatomic) NSDecimalNumber *NetPrice; ///< NetPrice - Edm.Decimal
@property (strong, nonatomic) NSString *UoM; ///< UoM - Edm.String
@property (strong, nonatomic) NSNumber *Quantity; ///< Int2 - Edm.Int16
@property (strong, nonatomic) NSString *Plant; ///< Plant - Edm.String
@property (strong, nonatomic) NSString *Description; ///< Description - Edm.String
@property (strong, nonatomic) NSString *Material; ///< Material - Edm.String
@property (strong, nonatomic) NSString *ItemNumber; ///< ItemNumber - Edm.String
@property (strong, nonatomic) NSString *OrderID; ///< OrderID - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *SalesDocumentQuery;
@property (strong, nonatomic) NSMutableArray *SalesDocument;

#pragma mark Static Methods
/**
 Static method that returns an array of SalesDocumentItem entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to SalesDocumentItem entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of SalesDocumentItem entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseSalesDocumentItemEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of SalesDocumentItem entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to SalesDocumentItem entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of SalesDocumentItem entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedSalesDocumentItemEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single SalesDocumentItem entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a SalesDocumentItem entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a SalesDocumentItem entity. Returns nil if the data in invalid.
*/
+ (SalesDocumentItem *)parseSalesDocumentItemEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single SalesDocumentItem entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a SalesDocumentItem entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a SalesDocumentItem entity. Returns nil if the data in invalid.
*/
+ (SalesDocumentItem *)parseExpandedSalesDocumentItemEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of SalesDocumentItem objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of SalesDocumentItem objects.
*/
+ (NSMutableArray *)createSalesDocumentItemEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads SalesDocument details for this entity from the provided data.
 @param aData The NSData containing the SalesDocument information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadSalesDocumentWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - MediaForBusinessPartner
@interface MediaForBusinessPartner : BaseEntityType {
	NSString *m_BusinessPartnerID;
	NSNumber *m_FileSize;
	NSString *m_FileName;
	NSString *m_MimeType;
	NSString *m_MediaID;
	MediaLink *m_mediaLinkRead;
	MediaLink *m_mediaLinkEdit;

}

@property (strong, nonatomic) NSString *BusinessPartnerID; ///< BusinessPartnerID - Edm.String
@property (strong, nonatomic) NSNumber *FileSize; ///< Int2 - Edm.Int16
@property (strong, nonatomic) NSString *FileName; ///< FileName - Edm.String
@property (strong, nonatomic) NSString *MimeType; ///< MimeType - Edm.String
@property (strong, nonatomic) NSString *MediaID; ///< MediaID - Edm.String
#pragma mark Entity Media Link Properties
@property (strong, readonly) MediaLink *mediaLinkRead; ///< Media Link Read - Holds the ODataQuery and Content-Type of the media link for read
@property (strong, readonly) MediaLink *mediaLinkEdit; ///< Media Link Edit - Holds the ODataQuery and Content-Type of the media link for update

#pragma mark Static Methods
/**
 Static method that returns an array of MediaForBusinessPartner entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to MediaForBusinessPartner entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MediaForBusinessPartner entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseMediaForBusinessPartnerEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of MediaForBusinessPartner entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to MediaForBusinessPartner entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MediaForBusinessPartner entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedMediaForBusinessPartnerEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single MediaForBusinessPartner entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a MediaForBusinessPartner entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MediaForBusinessPartner entity. Returns nil if the data in invalid.
*/
+ (MediaForBusinessPartner *)parseMediaForBusinessPartnerEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single MediaForBusinessPartner entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a MediaForBusinessPartner entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MediaForBusinessPartner entity. Returns nil if the data in invalid.
*/
+ (MediaForBusinessPartner *)parseExpandedMediaForBusinessPartnerEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of MediaForBusinessPartner objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of MediaForBusinessPartner objects.
*/
+ (NSMutableArray *)createMediaForBusinessPartnerEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - UserSetting
@interface UserSetting : BaseEntityType {
	NSString *m_EmployeeID;

}

@property (strong, nonatomic) NSString *EmployeeID; ///< EmployeeID - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of UserSetting entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to UserSetting entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of UserSetting entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseUserSettingEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of UserSetting entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to UserSetting entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of UserSetting entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedUserSettingEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single UserSetting entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a UserSetting entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a UserSetting entity. Returns nil if the data in invalid.
*/
+ (UserSetting *)parseUserSettingEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single UserSetting entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a UserSetting entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a UserSetting entity. Returns nil if the data in invalid.
*/
+ (UserSetting *)parseExpandedUserSettingEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of UserSetting objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of UserSetting objects.
*/
+ (NSMutableArray *)createUserSettingEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - MaterialGroup
@interface MaterialGroup : BaseEntityType {
	NSString *m_Description;
	NSString *m_MaterialGroupID;
    ODataQuery *m_MaterialSetQuery;
	NSMutableArray *m_MaterialSet;

}

@property (strong, nonatomic) NSString *Description; ///< Description - Edm.String
@property (strong, nonatomic) NSString *MaterialGroupID; ///< Material Group - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *MaterialSetQuery;
@property (strong, nonatomic) NSMutableArray *MaterialSet;

#pragma mark Static Methods
/**
 Static method that returns an array of MaterialGroup entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to MaterialGroup entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MaterialGroup entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseMaterialGroupEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of MaterialGroup entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to MaterialGroup entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MaterialGroup entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedMaterialGroupEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single MaterialGroup entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a MaterialGroup entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MaterialGroup entity. Returns nil if the data in invalid.
*/
+ (MaterialGroup *)parseMaterialGroupEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single MaterialGroup entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a MaterialGroup entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MaterialGroup entity. Returns nil if the data in invalid.
*/
+ (MaterialGroup *)parseExpandedMaterialGroupEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of MaterialGroup objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of MaterialGroup objects.
*/
+ (NSMutableArray *)createMaterialGroupEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads MaterialSet details for this entity from the provided data.
 @param aData The NSData containing the MaterialSet information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadMaterialSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end

#pragma mark - MediaForContactPerson
@interface MediaForContactPerson : BaseEntityType {
	NSString *m_RelatedPartnerID;
	NSNumber *m_FileSize;
	NSString *m_FileName;
	NSString *m_MimeType;
	NSString *m_MediaID;
	NSString *m_ContactPersonID;
	MediaLink *m_mediaLinkRead;
	MediaLink *m_mediaLinkEdit;

}

@property (strong, nonatomic) NSString *RelatedPartnerID; ///< RelatedPartnerID - Edm.String
@property (strong, nonatomic) NSNumber *FileSize; ///< Int2 - Edm.Int16
@property (strong, nonatomic) NSString *FileName; ///< FileName - Edm.String
@property (strong, nonatomic) NSString *MimeType; ///< MimeType - Edm.String
@property (strong, nonatomic) NSString *MediaID; ///< MediaID - Edm.String
@property (strong, nonatomic) NSString *ContactPersonID; ///< ContactPersonID - Edm.String
#pragma mark Entity Media Link Properties
@property (strong, readonly) MediaLink *mediaLinkRead; ///< Media Link Read - Holds the ODataQuery and Content-Type of the media link for read
@property (strong, readonly) MediaLink *mediaLinkEdit; ///< Media Link Edit - Holds the ODataQuery and Content-Type of the media link for update

#pragma mark Static Methods
/**
 Static method that returns an array of MediaForContactPerson entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to MediaForContactPerson entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MediaForContactPerson entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseMediaForContactPersonEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of MediaForContactPerson entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to MediaForContactPerson entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MediaForContactPerson entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedMediaForContactPersonEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single MediaForContactPerson entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a MediaForContactPerson entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MediaForContactPerson entity. Returns nil if the data in invalid.
*/
+ (MediaForContactPerson *)parseMediaForContactPersonEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single MediaForContactPerson entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a MediaForContactPerson entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MediaForContactPerson entity. Returns nil if the data in invalid.
*/
+ (MediaForContactPerson *)parseExpandedMediaForContactPersonEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of MediaForContactPerson objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of MediaForContactPerson objects.
*/
+ (NSMutableArray *)createMediaForContactPersonEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - MediaForMaterials
@interface MediaForMaterials : BaseEntityType {
	NSNumber *m_FileSize;
	NSString *m_FileName;
	NSString *m_MimeType;
	NSString *m_MediaID;
	NSString *m_MaterialNumber;
	MediaLink *m_mediaLinkRead;
	MediaLink *m_mediaLinkEdit;

}

@property (strong, nonatomic) NSNumber *FileSize; ///< Int2 - Edm.Int16
@property (strong, nonatomic) NSString *FileName; ///< FileName - Edm.String
@property (strong, nonatomic) NSString *MimeType; ///< MimeType - Edm.String
@property (strong, nonatomic) NSString *MediaID; ///< MediaID - Edm.String
@property (strong, nonatomic) NSString *MaterialNumber; ///< MaterialNumber - Edm.String
#pragma mark Entity Media Link Properties
@property (strong, readonly) MediaLink *mediaLinkRead; ///< Media Link Read - Holds the ODataQuery and Content-Type of the media link for read
@property (strong, readonly) MediaLink *mediaLinkEdit; ///< Media Link Edit - Holds the ODataQuery and Content-Type of the media link for update

#pragma mark Static Methods
/**
 Static method that returns an array of MediaForMaterials entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to MediaForMaterials entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MediaForMaterials entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseMediaForMaterialsEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of MediaForMaterials entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to MediaForMaterials entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MediaForMaterials entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedMediaForMaterialsEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single MediaForMaterials entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a MediaForMaterials entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MediaForMaterials entity. Returns nil if the data in invalid.
*/
+ (MediaForMaterials *)parseMediaForMaterialsEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single MediaForMaterials entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a MediaForMaterials entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MediaForMaterials entity. Returns nil if the data in invalid.
*/
+ (MediaForMaterials *)parseExpandedMediaForMaterialsEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of MediaForMaterials objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of MediaForMaterials objects.
*/
+ (NSMutableArray *)createMediaForMaterialsEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ECCSALESDATA_SRVService class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end



#pragma mark - ECCSALESDATA_SRV Service Proxy
@interface ECCSALESDATA_SRVService : BaseServiceObject {
    ODataQuery *m_ContactPersonsQuery;
    ODataQuery *m_BusinessPartnersQuery;
    ODataQuery *m_MaterialsQuery;
    ODataQuery *m_SalesDocumentsQuery;
    ODataQuery *m_SalesDocumentItemsQuery;
    ODataQuery *m_MediaCollectionForBusinessPartnerQuery;
    ODataQuery *m_UserSettingCollectionQuery;
    ODataQuery *m_MaterialGroupsQuery;
    ODataQuery *m_MediaForContactPersonSetQuery;
    ODataQuery *m_MediaForMaterialsSetQuery;

}

#pragma mark Query properties for service Entity Sets
/**
The OData query for the ContactPerson collection.
(Addressable false, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *ContactPersonsQuery;

/**
The OData query for the BusinessPartner collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *BusinessPartnersQuery;

/**
The OData query for the Material collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *MaterialsQuery;

/**
The OData query for the SalesDocument collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *SalesDocumentsQuery;

/**
The OData query for the SalesDocumentItem collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *SalesDocumentItemsQuery;

/**
The OData query for the MediaForBusinessPartner collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *MediaCollectionForBusinessPartnerQuery;

/**
The OData query for the UserSetting collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *UserSettingCollectionQuery;

/**
The OData query for the MaterialGroup collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *MaterialGroupsQuery;

/**
The OData query for the MediaForContactPerson collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *MediaForContactPersonSetQuery;

/**
The OData query for the MediaForMaterials collection.
(Addressable true, Requires-filter false, Creatable true, Updatable true, Deletable true)
*/
@property (strong, nonatomic) ODataQuery *MediaForMaterialsSetQuery;


#pragma mark Service Entity Set methods
/**
 Returns a collection of ContactPerson entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of ContactPerson entities.
*/
- (NSMutableArray *)getContactPersonsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific ContactPerson entity.
 @param RelatedPartnerID Part of the ContactPerson unique identifier (of type Edm.String).
 @param ContactPersonID Part of the ContactPerson unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getContactPersonsEntryQueryWithRelatedPartnerID:(NSString *)RelatedPartnerID andContactPersonID:(NSString *)ContactPersonID;

/**
 Returns the OData query for a specific ContactPerson entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param RelatedPartnerID Part of the ContactPerson unique identifier (of type Edm.String).
 @param ContactPersonID Part of the ContactPerson unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getContactPersonsEntryQueryTypedWithRelatedPartnerID:(NSString *)RelatedPartnerID andContactPersonID:(NSString *)ContactPersonID;

/**
 Returns a specific ContactPerson entity from the provided data.
 @param aData The NSData containing the ContactPerson information to be parsed to a ContactPerson entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a ContactPerson entity. Returns nil if the data in invalid.
*/
- (ContactPerson *)getContactPersonsEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of BusinessPartner entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of BusinessPartner entities.
*/
- (NSMutableArray *)getBusinessPartnersWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific BusinessPartner entity.
 @param BusinessPartnerID Part of the BusinessPartner unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getBusinessPartnersEntryQueryWithBusinessPartnerID:(NSString *)BusinessPartnerID;

/**
 Returns the OData query for a specific BusinessPartner entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param BusinessPartnerID Part of the BusinessPartner unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getBusinessPartnersEntryQueryTypedWithBusinessPartnerID:(NSString *)BusinessPartnerID;

/**
 Returns a specific BusinessPartner entity from the provided data.
 @param aData The NSData containing the BusinessPartner information to be parsed to a BusinessPartner entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a BusinessPartner entity. Returns nil if the data in invalid.
*/
- (BusinessPartner *)getBusinessPartnersEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of Material entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of Material entities.
*/
- (NSMutableArray *)getMaterialsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific Material entity.
 @param MaterialNumber Part of the Material unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMaterialsEntryQueryWithMaterialNumber:(NSString *)MaterialNumber;

/**
 Returns the OData query for a specific Material entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param MaterialNumber Part of the Material unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMaterialsEntryQueryTypedWithMaterialNumber:(NSString *)MaterialNumber;

/**
 Returns a specific Material entity from the provided data.
 @param aData The NSData containing the Material information to be parsed to a Material entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a Material entity. Returns nil if the data in invalid.
*/
- (Material *)getMaterialsEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of SalesDocument entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of SalesDocument entities.
*/
- (NSMutableArray *)getSalesDocumentsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific SalesDocument entity.
 @param OrderID Part of the SalesDocument unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getSalesDocumentsEntryQueryWithOrderID:(NSString *)OrderID;

/**
 Returns the OData query for a specific SalesDocument entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param OrderID Part of the SalesDocument unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getSalesDocumentsEntryQueryTypedWithOrderID:(NSString *)OrderID;

/**
 Returns a specific SalesDocument entity from the provided data.
 @param aData The NSData containing the SalesDocument information to be parsed to a SalesDocument entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a SalesDocument entity. Returns nil if the data in invalid.
*/
- (SalesDocument *)getSalesDocumentsEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of SalesDocumentItem entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of SalesDocumentItem entities.
*/
- (NSMutableArray *)getSalesDocumentItemsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific SalesDocumentItem entity.
 @param ItemNumber Part of the SalesDocumentItem unique identifier (of type Edm.String).
 @param OrderID Part of the SalesDocumentItem unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getSalesDocumentItemsEntryQueryWithItemNumber:(NSString *)ItemNumber andOrderID:(NSString *)OrderID;

/**
 Returns the OData query for a specific SalesDocumentItem entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param ItemNumber Part of the SalesDocumentItem unique identifier (of type Edm.String).
 @param OrderID Part of the SalesDocumentItem unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getSalesDocumentItemsEntryQueryTypedWithItemNumber:(NSString *)ItemNumber andOrderID:(NSString *)OrderID;

/**
 Returns a specific SalesDocumentItem entity from the provided data.
 @param aData The NSData containing the SalesDocumentItem information to be parsed to a SalesDocumentItem entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a SalesDocumentItem entity. Returns nil if the data in invalid.
*/
- (SalesDocumentItem *)getSalesDocumentItemsEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of MediaForBusinessPartner entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MediaForBusinessPartner entities.
*/
- (NSMutableArray *)getMediaCollectionForBusinessPartnerWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific MediaForBusinessPartner entity.
 @param BusinessPartnerID Part of the MediaForBusinessPartner unique identifier (of type Edm.String).
 @param MediaID Part of the MediaForBusinessPartner unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMediaCollectionForBusinessPartnerEntryQueryWithBusinessPartnerID:(NSString *)BusinessPartnerID andMediaID:(NSString *)MediaID;

/**
 Returns the OData query for a specific MediaForBusinessPartner entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param BusinessPartnerID Part of the MediaForBusinessPartner unique identifier (of type Edm.String).
 @param MediaID Part of the MediaForBusinessPartner unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMediaCollectionForBusinessPartnerEntryQueryTypedWithBusinessPartnerID:(NSString *)BusinessPartnerID andMediaID:(NSString *)MediaID;

/**
 Returns a specific MediaForBusinessPartner entity from the provided data.
 @param aData The NSData containing the MediaForBusinessPartner information to be parsed to a MediaForBusinessPartner entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MediaForBusinessPartner entity. Returns nil if the data in invalid.
*/
- (MediaForBusinessPartner *)getMediaCollectionForBusinessPartnerEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of UserSetting entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of UserSetting entities.
*/
- (NSMutableArray *)getUserSettingCollectionWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific UserSetting entity.
 @param EmployeeID Part of the UserSetting unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getUserSettingCollectionEntryQueryWithEmployeeID:(NSString *)EmployeeID;

/**
 Returns the OData query for a specific UserSetting entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param EmployeeID Part of the UserSetting unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getUserSettingCollectionEntryQueryTypedWithEmployeeID:(NSString *)EmployeeID;

/**
 Returns a specific UserSetting entity from the provided data.
 @param aData The NSData containing the UserSetting information to be parsed to a UserSetting entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a UserSetting entity. Returns nil if the data in invalid.
*/
- (UserSetting *)getUserSettingCollectionEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of MaterialGroup entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MaterialGroup entities.
*/
- (NSMutableArray *)getMaterialGroupsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific MaterialGroup entity.
 @param MaterialGroupID Part of the MaterialGroup unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMaterialGroupsEntryQueryWithMaterialGroupID:(NSString *)MaterialGroupID;

/**
 Returns the OData query for a specific MaterialGroup entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param MaterialGroupID Part of the MaterialGroup unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMaterialGroupsEntryQueryTypedWithMaterialGroupID:(NSString *)MaterialGroupID;

/**
 Returns a specific MaterialGroup entity from the provided data.
 @param aData The NSData containing the MaterialGroup information to be parsed to a MaterialGroup entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MaterialGroup entity. Returns nil if the data in invalid.
*/
- (MaterialGroup *)getMaterialGroupsEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of MediaForContactPerson entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MediaForContactPerson entities.
*/
- (NSMutableArray *)getMediaForContactPersonSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific MediaForContactPerson entity.
 @param RelatedPartnerID Part of the MediaForContactPerson unique identifier (of type Edm.String).
 @param MediaID Part of the MediaForContactPerson unique identifier (of type Edm.String).
 @param ContactPersonID Part of the MediaForContactPerson unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMediaForContactPersonSetEntryQueryWithRelatedPartnerID:(NSString *)RelatedPartnerID andMediaID:(NSString *)MediaID andContactPersonID:(NSString *)ContactPersonID;

/**
 Returns the OData query for a specific MediaForContactPerson entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param RelatedPartnerID Part of the MediaForContactPerson unique identifier (of type Edm.String).
 @param MediaID Part of the MediaForContactPerson unique identifier (of type Edm.String).
 @param ContactPersonID Part of the MediaForContactPerson unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMediaForContactPersonSetEntryQueryTypedWithRelatedPartnerID:(NSString *)RelatedPartnerID andMediaID:(NSString *)MediaID andContactPersonID:(NSString *)ContactPersonID;

/**
 Returns a specific MediaForContactPerson entity from the provided data.
 @param aData The NSData containing the MediaForContactPerson information to be parsed to a MediaForContactPerson entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MediaForContactPerson entity. Returns nil if the data in invalid.
*/
- (MediaForContactPerson *)getMediaForContactPersonSetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of MediaForMaterials entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of MediaForMaterials entities.
*/
- (NSMutableArray *)getMediaForMaterialsSetWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific MediaForMaterials entity.
 @param MediaID Part of the MediaForMaterials unique identifier (of type Edm.String).
 @param MaterialNumber Part of the MediaForMaterials unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMediaForMaterialsSetEntryQueryWithMediaID:(NSString *)MediaID andMaterialNumber:(NSString *)MaterialNumber;

/**
 Returns the OData query for a specific MediaForMaterials entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param MediaID Part of the MediaForMaterials unique identifier (of type Edm.String).
 @param MaterialNumber Part of the MediaForMaterials unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getMediaForMaterialsSetEntryQueryTypedWithMediaID:(NSString *)MediaID andMaterialNumber:(NSString *)MaterialNumber;

/**
 Returns a specific MediaForMaterials entity from the provided data.
 @param aData The NSData containing the MediaForMaterials information to be parsed to a MediaForMaterials entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a MediaForMaterials entity. Returns nil if the data in invalid.
*/
- (MediaForMaterials *)getMediaForMaterialsSetEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


#pragma mark Service Function Import methods
@end