/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.100.0
  
 File: SettingsUtilities.m
 Abstract: A utility class responsible for reading the application settings (as the service URL and the SAP client).
 
 */

#import "SettingsUtilities.h"


@implementation SettingsUtilities

+ (NSMutableDictionary *)findPreferenceIn:(NSArray *)list forKey:(NSString *)key
{
	for (NSMutableDictionary* pref in list) {
		NSString* value = [pref objectForKey:@"Key"];
		if ([value length] > 0 && [value isEqualToString:key]) {
			return pref;
		}
	}
	return nil;
}

+ (NSString *)getServiceUrlFromUserSettings
{	
	NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
	NSString *url = [defaults stringForKey:@"SAP_EndPointURL"];
	
	if (!url) {
		NSString *pathToBundle = [[NSBundle mainBundle] pathForResource:@"Settings" ofType:@"bundle"];
		NSMutableDictionary* rootPlist = [NSMutableDictionary dictionaryWithContentsOfFile:[NSString stringWithFormat:@"%@/Root.plist",pathToBundle]];
		NSMutableDictionary *preferences = [self findPreferenceIn:(NSArray*)[rootPlist objectForKey:@"PreferenceSpecifiers"] forKey:@"SAP_EndPointURL"];
		url = [preferences objectForKey:@"DefaultValue"];
		if (url) {
			NSDictionary *appDefaults = [NSDictionary dictionaryWithObject:url forKey:@"SAP_EndPointURL"];
			[defaults registerDefaults:appDefaults];
			[defaults synchronize];
		}
	}
	return url;
}

+ (NSString *)getBWServiceUrlFromUserSettings
{
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
	NSString *url = [defaults stringForKey:@"bwsystem"];
	
	if (!url) {
		NSString *pathToBundle = [[NSBundle mainBundle] pathForResource:@"Settings" ofType:@"bundle"];
		NSMutableDictionary* rootPlist = [NSMutableDictionary dictionaryWithContentsOfFile:[NSString stringWithFormat:@"%@/Root.plist",pathToBundle]];
		NSMutableDictionary *preferences = [self findPreferenceIn:(NSArray*)[rootPlist objectForKey:@"PreferenceSpecifiers"] forKey:@"bwsystem"];
		url = [preferences objectForKey:@"DefaultValue"];
		if (url) {
			NSDictionary *appDefaults = [NSDictionary dictionaryWithObject:url forKey:@"bwsystem"];
			[defaults registerDefaults:appDefaults];
			[defaults synchronize];
		}
	}
	return url;
}

+ (NSString *)getServiceClientFromUserSettings
{
	NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
	NSString *client = [defaults stringForKey:@"SAP_EndPointClient"];
	
	if (!client) {
		NSString *pathToBundle = [[NSBundle mainBundle] pathForResource:@"Settings" ofType:@"bundle"];
		NSMutableDictionary* rootPlist = [NSMutableDictionary dictionaryWithContentsOfFile:[NSString stringWithFormat:@"%@/Root.plist",pathToBundle]];
		NSMutableDictionary *preferences = [self findPreferenceIn:(NSArray*)[rootPlist objectForKey:@"PreferenceSpecifiers"] forKey:@"SAP_EndPointClient"];
		client = [preferences objectForKey:@"DefaultValue"];
		if (client) {
			NSDictionary *appDefaults = [NSDictionary dictionaryWithObject:client forKey:@"SAP_EndPointClient"];
			[defaults registerDefaults:appDefaults];
			[defaults synchronize];
		}
	}
	return client;
}

// gets the authentication type from the application settings
+ (NSString *)getAuthenticationTypeFromUserSettings
{
	NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
	NSString *authType = [defaults stringForKey:@"SAP_AuthenticationType"];
	
	if (!authType) {
		NSString *pathToBundle = [[NSBundle mainBundle] pathForResource:@"Settings" ofType:@"bundle"];
		NSMutableDictionary* rootPlist = [NSMutableDictionary dictionaryWithContentsOfFile:[NSString stringWithFormat:@"%@/Root.plist",pathToBundle]];
		NSMutableDictionary *preferences = [self findPreferenceIn:(NSArray*)[rootPlist objectForKey:@"PreferenceSpecifiers"] forKey:@"SAP_AuthenticationType"];
		authType = [preferences objectForKey:@"DefaultValue"];
		if (authType) {
			NSDictionary *appDefaults = [NSDictionary dictionaryWithObject:authType forKey:@"SAP_AuthenticationType"];
			[defaults registerDefaults:appDefaults];
			[defaults synchronize];
		}
	}
	return authType;
}

+ (NSString *)getUsernameFromUserSettings
{
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
	NSString *client = [defaults stringForKey:@"appuser"];
	
	if (!client) {
		NSString *pathToBundle = [[NSBundle mainBundle] pathForResource:@"Settings" ofType:@"bundle"];
		NSMutableDictionary* rootPlist = [NSMutableDictionary dictionaryWithContentsOfFile:[NSString stringWithFormat:@"%@/Root.plist",pathToBundle]];
		NSMutableDictionary *preferences = [self findPreferenceIn:(NSArray*)[rootPlist objectForKey:@"PreferenceSpecifiers"] forKey:@"appuser"];
		client = [preferences objectForKey:@"DefaultValue"];
		if (client) {
			NSDictionary *appDefaults = [NSDictionary dictionaryWithObject:client forKey:@"appuser"];
			[defaults registerDefaults:appDefaults];
			[defaults synchronize];
		}
	}
	return client;
}

+ (NSString *)getPasswordFromUserSettings
{
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
	NSString *client = [defaults stringForKey:@"appPassword"];
	
	if (!client) {
		NSString *pathToBundle = [[NSBundle mainBundle] pathForResource:@"Settings" ofType:@"bundle"];
		NSMutableDictionary* rootPlist = [NSMutableDictionary dictionaryWithContentsOfFile:[NSString stringWithFormat:@"%@/Root.plist",pathToBundle]];
		NSMutableDictionary *preferences = [self findPreferenceIn:(NSArray*)[rootPlist objectForKey:@"PreferenceSpecifiers"] forKey:@"appPassword"];
		client = [preferences objectForKey:@"DefaultValue"];
		if (client) {
			NSDictionary *appDefaults = [NSDictionary dictionaryWithObject:client forKey:@"appPassword"];
			[defaults registerDefaults:appDefaults];
			[defaults synchronize];
		}
	}
	return client;
}

+ (NSString *)getLoadImagesFromUserSettings
{
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
	NSString *client = [defaults stringForKey:@"loadimages"];
	
	if (client == nil) {
		NSString *pathToBundle = [[NSBundle mainBundle] pathForResource:@"Settings" ofType:@"bundle"];
		NSMutableDictionary* rootPlist = [NSMutableDictionary dictionaryWithContentsOfFile:[NSString stringWithFormat:@"%@/Root.plist",pathToBundle]];
		NSMutableDictionary *preferences = [self findPreferenceIn:(NSArray*)[rootPlist objectForKey:@"PreferenceSpecifiers"] forKey:@"loadimages"];
		client = [preferences objectForKey:@"DefaultValue"];
		if (client) {
			NSDictionary *appDefaults = [NSDictionary dictionaryWithObject:client forKey:@"loadimages"];
			[defaults registerDefaults:appDefaults];
			[defaults synchronize];
		}
	}
	return client;
}

+ (BOOL)getDemoStatus
{
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
	BOOL demostatus = [defaults boolForKey:@"demo"];
    
    return demostatus;
}

@end
