/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.100.0
  
 File: SettingsUtilities.h
 Abstract: A utility class responsible for reading the application settings (as the service URL and the SAP client).
 
 */

#import <Foundation/Foundation.h>

#define BASIC_AUTHENTICATION @"Basic"

/**
 A utility class responsible for reading the application settings (as the service URL and the SAP client).
 */
@interface SettingsUtilities : NSObject

/**
 @return The service URL from the application settings.
*/
+ (NSString *)getServiceUrlFromUserSettings;
+ (NSString *)getBWServiceUrlFromUserSettings;
/**
 @return The service SAP Client from the application settings.
 */
+ (NSString *)getServiceClientFromUserSettings;

/**
 @return The authentication type from the application settings.
 */
+ (NSString *)getAuthenticationTypeFromUserSettings;

+ (NSString *)getUsernameFromUserSettings;

+ (NSString *)getPasswordFromUserSettings;

+ (NSString *)getLoadImagesFromUserSettings;

+ (BOOL)getDemoStatus;

@end
