/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.300.0
  
 File: ZAPP_AR01Service.h
 Abstract: The generated proxy classes for the ZAPP_AR01 Service. Service Version: 1.   
*/

#import <Foundation/Foundation.h>
#import "BaseEntityType.h"
#import "BaseComplexType.h"
#import "BaseServiceObject.h"

#pragma mark - Complex Types



#pragma mark - Entity Types

/**
 Each of the following classes represents an entity-type of the ZAPP_AR01Service service.
 
 Any entity-type class should be used as following:
 
 1. The entity object may represent an existing entry of an appropriate service collection,
 if the object is initialized using data returned from an appropriate service call.
 This may be achieved by using the initWithSDMEntry: constructor,
 or using the static methods creating the entity object (parse<entity-type-name>EntriesWithData,
 parse<entity-type-name>EntryWithData, and create<entity-type-name>EntriesForSDMEntries).
 
 For retrieving the entry data, use the appropriate query properties and methods of this class 
 and of the ZAPP_AR01Service class, and then execute the request (see the SDMConnectivityHelper class).
 
 2. Another option is to use this entity object as a new entry to create in an appropriate service collection.
 In this case, use the init constructor and set the appropriate properties. 
 Note that some features (as navigation properties) are not available in this mode (since it is not yet an actual service entry).
 Use the SDMConnectivityHelper class and the getXMLForCreateRequest method of the BaseServiceObject class, to send the 'create' request.
 Then use the service response for constructing a new object, in order to represent the entry as existed in the service. 
 
 In both operation modes, setting the entity property values will not affect the service until the changes are sent to the server.
 For sending changes to the server, see the SDMConnectivityHelper class and the getXMLForRequest methods of the BaseServiceObject class.
 It is recommended to use the server response for constructing a new object, in order to represent the entry as existed in the service.
 
 Note: For proper behavior of this class, make sure to initialize the ZAPP_AR01Service class
 in your application, before initializing the entity-type class objects.
*/
 

#pragma mark - AZAPP_AR01Result
@interface AZAPP_AR01Result : BaseEntityType {
	NSString *m_ROWID;
	NSString *m_A0DEBITOR;
	NSString *m_A0DEBITOR_T;
	NSDecimalNumber *m_A006EI3ULWC7I23F67E6D3RU2K;
	NSString *m_A006EI3ULWC7I23F67E6D3RU2K_F;
	NSDecimalNumber *m_A006EI3ULWC7I23F67E6D3SD18;
	NSString *m_A006EI3ULWC7I23F67E6D3SD18_F;
	NSDecimalNumber *m_A006EI3ULWC7I23F67E6D3SVZW;
	NSString *m_A006EI3ULWC7I23F67E6D3SVZW_F;
	NSDecimalNumber *m_A006EI3ULWC7I23F67E6D3TEYK;
	NSString *m_A006EI3ULWC7I23F67E6D3TEYK_F;
	NSDecimalNumber *m_A006EI3ULWC7I23F67E6D3TXX8;
	NSString *m_A006EI3ULWC7I23F67E6D3TXX8_F;
	NSDecimalNumber *m_A006EI3ULWC7I23F67E6D3UGVW;
	NSString *m_A006EI3ULWC7I23F67E6D3UGVW_F;
	NSDecimalNumber *m_A006EI3ULWC7I23F67E6D3UZUK;
	NSString *m_A006EI3ULWC7I23F67E6D3UZUK_F;
	NSString *m_ISTOTAL;

}

@property (strong, nonatomic) NSString *ROWID; ///< ROWID - Edm.String
@property (strong, nonatomic) NSString *A0DEBITOR; ///< Customer - Edm.String
@property (strong, nonatomic) NSString *A0DEBITOR_T; ///< Customer - Edm.String
@property (strong, nonatomic) NSDecimalNumber *A006EI3ULWC7I23F67E6D3RU2K; ///< Balance - Edm.Decimal
@property (strong, nonatomic) NSString *A006EI3ULWC7I23F67E6D3RU2K_F; ///< Balance (Formatted) - Edm.String
@property (strong, nonatomic) NSDecimalNumber *A006EI3ULWC7I23F67E6D3SD18; ///< 0 Days - Edm.Decimal
@property (strong, nonatomic) NSString *A006EI3ULWC7I23F67E6D3SD18_F; ///< 0 Days (Formatted) - Edm.String
@property (strong, nonatomic) NSDecimalNumber *A006EI3ULWC7I23F67E6D3SVZW; ///< 1 - 30 Days - Edm.Decimal
@property (strong, nonatomic) NSString *A006EI3ULWC7I23F67E6D3SVZW_F; ///< 1 - 30 Days (Formatted) - Edm.String
@property (strong, nonatomic) NSDecimalNumber *A006EI3ULWC7I23F67E6D3TEYK; ///< 31 - 60 Days - Edm.Decimal
@property (strong, nonatomic) NSString *A006EI3ULWC7I23F67E6D3TEYK_F; ///< 31 - 60 Days (Formatted) - Edm.String
@property (strong, nonatomic) NSDecimalNumber *A006EI3ULWC7I23F67E6D3TXX8; ///< 61 - 180 Days - Edm.Decimal
@property (strong, nonatomic) NSString *A006EI3ULWC7I23F67E6D3TXX8_F; ///< 61 - 180 Days (Formatted) - Edm.String
@property (strong, nonatomic) NSDecimalNumber *A006EI3ULWC7I23F67E6D3UGVW; ///< 181 - 365 Days - Edm.Decimal
@property (strong, nonatomic) NSString *A006EI3ULWC7I23F67E6D3UGVW_F; ///< 181 - 365 Days (Formatted) - Edm.String
@property (strong, nonatomic) NSDecimalNumber *A006EI3ULWC7I23F67E6D3UZUK; ///< > 365 Days - Edm.Decimal
@property (strong, nonatomic) NSString *A006EI3ULWC7I23F67E6D3UZUK_F; ///< > 365 Days (Formatted) - Edm.String
@property (strong, nonatomic) NSString *ISTOTAL; ///< Total/Subtotal Columns - Edm.String

#pragma mark Static Methods
/**
 Static method that returns an array of AZAPP_AR01Result entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to AZAPP_AR01Result entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of AZAPP_AR01Result entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseAZAPP_AR01ResultEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of AZAPP_AR01Result entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to AZAPP_AR01Result entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of AZAPP_AR01Result entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedAZAPP_AR01ResultEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single AZAPP_AR01Result entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a AZAPP_AR01Result entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a AZAPP_AR01Result entity. Returns nil if the data in invalid.
*/
+ (AZAPP_AR01Result *)parseAZAPP_AR01ResultEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single AZAPP_AR01Result entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a AZAPP_AR01Result entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a AZAPP_AR01Result entity. Returns nil if the data in invalid.
*/
+ (AZAPP_AR01Result *)parseExpandedAZAPP_AR01ResultEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of AZAPP_AR01Result objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of AZAPP_AR01Result objects.
*/
+ (NSMutableArray *)createAZAPP_AR01ResultEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZAPP_AR01Service class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZAPP_AR01Service class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;



@end

#pragma mark - AZAPP_AR01Parameters
@interface AZAPP_AR01Parameters : BaseEntityType {
	NSString *m_A0P_COCD;
	NSString *m_A0P_COCDText;
	NSString *m_A0S_DEBITFrom;
	NSString *m_A0S_DEBITTo;
	NSString *m_A0S_DEBITText;
	NSNumber *m_A0P_KEYDT;
	NSString *m_A0P_KEYDTText;
    ODataQuery *m_ResultsQuery;
	NSMutableArray *m_Results;

}

@property (strong, nonatomic) NSString *A0P_COCD; ///< Company Code (Single Value Entry, Required) - Edm.String
@property (strong, nonatomic) NSString *A0P_COCDText; ///< Company Code (Single Value Entry, Required) (Text) - Edm.String
@property (strong, nonatomic) NSString *A0S_DEBITFrom; ///< Customer (Selection Options, Optional) - Edm.String
@property (strong, nonatomic) NSString *A0S_DEBITTo; ///< Customer (Selection Options, Optional) - Edm.String
@property (strong, nonatomic) NSString *A0S_DEBITText; ///< Customer (Selection Options, Optional) (Text) - Edm.String
@property (strong, nonatomic) NSNumber *A0P_KEYDT; ///< Key due date - Edm.Double
@property (strong, nonatomic) NSString *A0P_KEYDTText; ///< Key due date (Text) - Edm.String
#pragma mark Entity Navigation Properties
@property (strong, nonatomic) ODataQuery *ResultsQuery;
@property (strong, nonatomic) NSMutableArray *Results;

#pragma mark Static Methods
/**
 Static method that returns an array of AZAPP_AR01Parameters entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to AZAPP_AR01Parameters entities.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of AZAPP_AR01Parameters entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseAZAPP_AR01ParametersEntriesWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of AZAPP_AR01Parameters entities and their related entities from the provided data.
 @param aData The NSData containing an Atom Feed including the entries to be parsed to AZAPP_AR01Parameters entities.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of AZAPP_AR01Parameters entities. Returns nil if the data in invalid.
*/
+ (NSMutableArray *)parseExpandedAZAPP_AR01ParametersEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Returns a single AZAPP_AR01Parameters entity from the provided data.
 @param aData The NSData containing an Atom Entry including the entry to be parsed to a AZAPP_AR01Parameters entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a AZAPP_AR01Parameters entity. Returns nil if the data in invalid.
*/
+ (AZAPP_AR01Parameters *)parseAZAPP_AR01ParametersEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns a single AZAPP_AR01Parameters entity and related entities from the provided data.
 @param aData The NSData containing an Atom Entry including the entry and its related entries to be parsed to a AZAPP_AR01Parameters entity.
 @param aServiceDocument The SDMODataServiceDocument that represents the service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a AZAPP_AR01Parameters entity. Returns nil if the data in invalid.
*/
+ (AZAPP_AR01Parameters *)parseExpandedAZAPP_AR01ParametersEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError * __autoreleasing *)error;

/**
 Static method that returns an array of AZAPP_AR01Parameters objects from a given array of SDMODataEntry objects.
 @param sdmEntries Array of SDMODataEntry objects.
 @return Array of AZAPP_AR01Parameters objects.
*/
+ (NSMutableArray *)createAZAPP_AR01ParametersEntriesForSDMEntries:(NSMutableArray *)sdmEntries;

/**
 Static method that loads the entity schema of this type.
 This method is called when the ZAPP_AR01Service class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService;

/**
 Static method that loads all of the entity type property labels.
 This method is called when the ZAPP_AR01Service class is initialized.
 @param aService Service document object containing all of the entity type properties.
*/
+ (void)loadLabels:(SDMODataServiceDocument *)aService;

/**
 Static method that returns the label for a given property name.
 @param aPropertyName Property name.
 @return Property label.
*/
+ (NSString *)getLabelForProperty:(NSString *)aPropertyName;


#pragma mark Entity Navigation Property loading methods
/**
 Navigation property. Loads Results details for this entity from the provided data.
 @param aData The NSData containing the Results information to be parsed.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns YES if the method completed successfully.
*/
- (BOOL)loadResultsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


@end



#pragma mark - ZAPP_AR01 Service Proxy
@interface ZAPP_AR01Service : BaseServiceObject {
    ODataQuery *m_AZAPP_AR01Query;
    ODataQuery *m_AZAPP_AR01ResultsQuery;

}

#pragma mark Query properties for service Entity Sets
/**
The OData query for the AZAPP_AR01Parameters collection.
(Addressable true, Requires-filter false, Creatable false, Updatable false, Deletable false)
*/
@property (strong, nonatomic) ODataQuery *AZAPP_AR01Query;

/**
The OData query for the AZAPP_AR01Result collection.
(Addressable false, Requires-filter false, Creatable false, Updatable false, Deletable false)
*/
@property (strong, nonatomic) ODataQuery *AZAPP_AR01ResultsQuery;


#pragma mark Service Entity Set methods
/**
 Returns a collection of AZAPP_AR01Parameters entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of AZAPP_AR01Parameters entities.
*/
- (NSMutableArray *)getAZAPP_AR01WithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific AZAPP_AR01Parameters entity.
 @param A0P_COCD Part of the AZAPP_AR01Parameters unique identifier (of type Edm.String).
 @param A0S_DEBITFrom Part of the AZAPP_AR01Parameters unique identifier (of type Edm.String).
 @param A0S_DEBITTo Part of the AZAPP_AR01Parameters unique identifier (of type Edm.String).
 @param A0P_KEYDT Part of the AZAPP_AR01Parameters unique identifier (of type Edm.Double).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getAZAPP_AR01EntryQueryWithA0P_COCD:(NSString *)A0P_COCD andA0S_DEBITFrom:(NSString *)A0S_DEBITFrom andA0S_DEBITTo:(NSString *)A0S_DEBITTo andA0P_KEYDT:(NSString *)A0P_KEYDT;

/**
 Returns the OData query for a specific AZAPP_AR01Parameters entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param A0P_COCD Part of the AZAPP_AR01Parameters unique identifier (of type Edm.String).
 @param A0S_DEBITFrom Part of the AZAPP_AR01Parameters unique identifier (of type Edm.String).
 @param A0S_DEBITTo Part of the AZAPP_AR01Parameters unique identifier (of type Edm.String).
 @param A0P_KEYDT Part of the AZAPP_AR01Parameters unique identifier (of type Edm.Double).
 @return Returns an OData query object.
*/
- (ODataQuery *)getAZAPP_AR01EntryQueryTypedWithA0P_COCD:(NSString *)A0P_COCD andA0S_DEBITFrom:(NSString *)A0S_DEBITFrom andA0S_DEBITTo:(NSString *)A0S_DEBITTo andA0P_KEYDT:(NSNumber *)A0P_KEYDT;

/**
 Returns a specific AZAPP_AR01Parameters entity from the provided data.
 @param aData The NSData containing the AZAPP_AR01Parameters information to be parsed to a AZAPP_AR01Parameters entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a AZAPP_AR01Parameters entity. Returns nil if the data in invalid.
*/
- (AZAPP_AR01Parameters *)getAZAPP_AR01EntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;
/**
 Returns a collection of AZAPP_AR01Result entities from the data returned by the OData service.
 @param aData The NSData returned from the OData service.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns an array of AZAPP_AR01Result entities.
*/
- (NSMutableArray *)getAZAPP_AR01ResultsWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;

/**
 Returns the OData query for a specific AZAPP_AR01Result entity.
 @param ROWID Part of the AZAPP_AR01Result unique identifier (of type Edm.String).
 Note: pass the parameter values exactly as they should appear in the query URL, 
 in the correct format according to their types 
 (for more information, see: http://www.odata.org/documentation/overview#AbstractTypeSystem).
 @return Returns an OData query object.
*/
- (ODataQuery *)getAZAPP_AR01ResultsEntryQueryWithROWID:(NSString *)ROWID;

/**
 Returns the OData query for a specific AZAPP_AR01Result entity with typed parameters.
 Note: This method is relevant only for OData compliant services.
 @param ROWID Part of the AZAPP_AR01Result unique identifier (of type Edm.String).
 @return Returns an OData query object.
*/
- (ODataQuery *)getAZAPP_AR01ResultsEntryQueryTypedWithROWID:(NSString *)ROWID;

/**
 Returns a specific AZAPP_AR01Result entity from the provided data.
 @param aData The NSData containing the AZAPP_AR01Result information to be parsed to a AZAPP_AR01Result entity.
 @param error A pointer to an NSError object that will hold the error info if one occurs.
 @return Returns a AZAPP_AR01Result entity. Returns nil if the data in invalid.
*/
- (AZAPP_AR01Result *)getAZAPP_AR01ResultsEntryWithData:(NSData *)aData error:(NSError * __autoreleasing *)error;


#pragma mark Service Function Import methods
@end