/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.300.0
  
 File: ZAPP_ORDER02Service.h
 Abstract: The generated proxy classes for the ZAPP_ORDER02 Service. Service Version: 1.  
*/

#import "ZAPP_ORDER02Service.h"
#import "BaseODataObject.h"
#import "Logger.h"
#import "SDMODataEntitySchema.h"
#import "SDMODataCollection.h"
#import "SDMODataFunctionImport.h"
#import "TypeConverter.h"

#define ZAPP_ORDER02_SERVICE_DOCUMENT @"ZAPP_ORDER02ServiceDocument"
#define ZAPP_ORDER02_SERVICE_METADATA @"ZAPP_ORDER02ServiceMetadata"

#pragma mark - Complex Types



#pragma mark - Entity Types


#pragma mark - AZAPP_ORDER02Result
@implementation AZAPP_ORDER02Result 

@synthesize ROWID = m_ROWID;
@synthesize A0SOLD_TO = m_A0SOLD_TO;
@synthesize A0SOLD_TO_T = m_A0SOLD_TO_T;
@synthesize A0DOC_CATEG = m_A0DOC_CATEG;
@synthesize A0DOC_CATEG_T = m_A0DOC_CATEG_T;
@synthesize A0MATERIAL__0MATL_GROUP = m_A0MATERIAL__0MATL_GROUP;
@synthesize A0MATERIAL__0MATL_GROUP_T = m_A0MATERIAL__0MATL_GROUP_T;
@synthesize A006EI3ULWC7I23DR830YQPUD8 = m_A006EI3ULWC7I23DR830YQPUD8;
@synthesize A006EI3ULWC7I23DR830YQPUD8_F = m_A006EI3ULWC7I23DR830YQPUD8_F;
@synthesize A006EI3ULWC7I23F3EUWUWJ858 = m_A006EI3ULWC7I23F3EUWUWJ858;
@synthesize A006EI3ULWC7I23F3EUWUWJ858_F = m_A006EI3ULWC7I23F3EUWUWJ858_F;
@synthesize ISTOTAL = m_ISTOTAL;

static NSMutableDictionary *aZAPP_ORDER02ResultLabels = nil;
static SDMODataEntitySchema *aZAPP_ORDER02ResultEntitySchema = nil;

- (id)init
{
    self = [super init];
    if (self) {
        m_SDMEntry = [BaseEntityType createEmptySDMODataEntryWithSchema:aZAPP_ORDER02ResultEntitySchema error:nil];
        if (!m_SDMEntry) {
            return nil;
        }        
        m_properties = nil;
        m_baseUrl = nil;
    }
    return self;
}



- (SDMODataEntry *)buildSDMEntryFromPropertiesAndReturnError:(NSError **)error
{
    if (m_SDMEntry) {
        NSError *innerError = nil;
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.ROWID forSDMPropertyWithName:@"ROWID" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A0SOLD_TO forSDMPropertyWithName:@"A0SOLD_TO" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A0SOLD_TO_T forSDMPropertyWithName:@"A0SOLD_TO_T" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A0DOC_CATEG forSDMPropertyWithName:@"A0DOC_CATEG" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A0DOC_CATEG_T forSDMPropertyWithName:@"A0DOC_CATEG_T" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A0MATERIAL__0MATL_GROUP forSDMPropertyWithName:@"A0MATERIAL__0MATL_GROUP" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A0MATERIAL__0MATL_GROUP_T forSDMPropertyWithName:@"A0MATERIAL__0MATL_GROUP_T" error:&innerError];
    	[BaseODataObject setDecimalValueForSDMEntry:m_SDMEntry withValue:self.A006EI3ULWC7I23DR830YQPUD8 forSDMPropertyWithName:@"A006EI3ULWC7I23DR830YQPUD8" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A006EI3ULWC7I23DR830YQPUD8_F forSDMPropertyWithName:@"A006EI3ULWC7I23DR830YQPUD8_F" error:&innerError];
    	[BaseODataObject setDecimalValueForSDMEntry:m_SDMEntry withValue:self.A006EI3ULWC7I23F3EUWUWJ858 forSDMPropertyWithName:@"A006EI3ULWC7I23F3EUWUWJ858" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A006EI3ULWC7I23F3EUWUWJ858_F forSDMPropertyWithName:@"A006EI3ULWC7I23F3EUWUWJ858_F" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.ISTOTAL forSDMPropertyWithName:@"ISTOTAL" error:&innerError];
        if (innerError) {
            if (error) {
                *error = innerError;
            }
            return nil;
        }
	}
    return m_SDMEntry;
}

+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService
{
    SDMODataCollection *collectionSchema = [aService.schema getCollectionByName:@"AZAPP_ORDER02Results" workspaceOfCollection:nil];
    aZAPP_ORDER02ResultEntitySchema = collectionSchema.entitySchema;
}

+ (void)loadLabels:(SDMODataServiceDocument *)aService
{
		NSMutableDictionary *properties = [BaseODataObject getSchemaPropertiesFromCollection:@"AZAPP_ORDER02Results" andService:aService];
    	if (properties) {    
	    	aZAPP_ORDER02ResultLabels = [NSMutableDictionary dictionary];
	    	for (SDMODataPropertyInfo *property in [properties allValues]) {
	        	[aZAPP_ORDER02ResultLabels setValue:property.label forKey:property.name];
	    	}
	    }
	    else {
        	LOGERROR(@"Failed to load SAP labels from service metadata");
    	}
}


+ (NSString *)getLabelForProperty:(NSString *)aPropertyName
{
    return [BaseODataObject getLabelFromDictionary:aZAPP_ORDER02ResultLabels forProperty:aPropertyName];
}

- (void)loadProperties
{
    [super loadProperties];
	m_ROWID = [self getStringValueForSDMPropertyWithName:@"ROWID"];
	m_A0SOLD_TO = [self getStringValueForSDMPropertyWithName:@"A0SOLD_TO"];
	m_A0SOLD_TO_T = [self getStringValueForSDMPropertyWithName:@"A0SOLD_TO_T"];
	m_A0DOC_CATEG = [self getStringValueForSDMPropertyWithName:@"A0DOC_CATEG"];
	m_A0DOC_CATEG_T = [self getStringValueForSDMPropertyWithName:@"A0DOC_CATEG_T"];
	m_A0MATERIAL__0MATL_GROUP = [self getStringValueForSDMPropertyWithName:@"A0MATERIAL__0MATL_GROUP"];
	m_A0MATERIAL__0MATL_GROUP_T = [self getStringValueForSDMPropertyWithName:@"A0MATERIAL__0MATL_GROUP_T"];
	m_A006EI3ULWC7I23DR830YQPUD8 = [self getDecimalValueForSDMPropertyWithName:@"A006EI3ULWC7I23DR830YQPUD8"];
	m_A006EI3ULWC7I23DR830YQPUD8_F = [self getStringValueForSDMPropertyWithName:@"A006EI3ULWC7I23DR830YQPUD8_F"];
	m_A006EI3ULWC7I23F3EUWUWJ858 = [self getDecimalValueForSDMPropertyWithName:@"A006EI3ULWC7I23F3EUWUWJ858"];
	m_A006EI3ULWC7I23F3EUWUWJ858_F = [self getStringValueForSDMPropertyWithName:@"A006EI3ULWC7I23F3EUWUWJ858_F"];
	m_ISTOTAL = [self getStringValueForSDMPropertyWithName:@"ISTOTAL"];
}

+ (NSMutableArray *)createAZAPP_ORDER02ResultEntriesForSDMEntries:(NSMutableArray *)sdmEntries
{
    NSMutableArray *entries = [NSMutableArray array];
    for (SDMODataEntry *entry in sdmEntries) {
        AZAPP_ORDER02Result *aZAPP_ORDER02ResultObject = [[AZAPP_ORDER02Result alloc] initWithSDMEntry:entry];
        [entries addObject:aZAPP_ORDER02ResultObject];
    }
    return entries;
}


+ (NSMutableArray *)parseAZAPP_ORDER02ResultEntriesWithData:(NSData *)aData error:(NSError **)error
{
    NSMutableArray *sdmEntries = [BaseEntityType getSDMEntriesForEntitySchema:aZAPP_ORDER02ResultEntitySchema andData:aData error:error];
    if (!sdmEntries) {
    	return nil;
    }
	return [AZAPP_ORDER02Result createAZAPP_ORDER02ResultEntriesForSDMEntries:sdmEntries];
}

+ (NSMutableArray *)parseExpandedAZAPP_ORDER02ResultEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError **)error
{
    NSMutableArray *sdmEntries = [BaseEntityType getExpandedSDMEntriesForEntitySchema:aZAPP_ORDER02ResultEntitySchema andData:aData andServiceDocument:aServiceDocument error:error];
    if (!sdmEntries) {
    	return nil;
    }
	return [AZAPP_ORDER02Result createAZAPP_ORDER02ResultEntriesForSDMEntries:sdmEntries];
}

+ (AZAPP_ORDER02Result *)parseAZAPP_ORDER02ResultEntryWithData:(NSData *)aData error:(NSError **)error
{
    NSMutableArray *aZAPP_ORDER02ResultEntries = [AZAPP_ORDER02Result parseAZAPP_ORDER02ResultEntriesWithData:aData error:error];
    if (!aZAPP_ORDER02ResultEntries) {
    	return nil;
    }
    return (AZAPP_ORDER02Result *)[AZAPP_ORDER02Result getFirstObjectFromArray:aZAPP_ORDER02ResultEntries];
}

+ (AZAPP_ORDER02Result *)parseExpandedAZAPP_ORDER02ResultEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError **)error
{
	NSMutableArray *sdmEntries = [BaseEntityType getExpandedSDMEntriesForEntitySchema:aZAPP_ORDER02ResultEntitySchema andData:aData andServiceDocument:aServiceDocument error:error];
    NSMutableArray *aZAPP_ORDER02ResultEntries = [AZAPP_ORDER02Result createAZAPP_ORDER02ResultEntriesForSDMEntries:sdmEntries];
	return (AZAPP_ORDER02Result *)[AZAPP_ORDER02Result getFirstObjectFromArray:aZAPP_ORDER02ResultEntries];
}



@end

#pragma mark - AZAPP_ORDER02Parameters
@implementation AZAPP_ORDER02Parameters 

@synthesize ZDOCCAT1From = m_ZDOCCAT1From;
@synthesize ZDOCCAT1To = m_ZDOCCAT1To;
@synthesize ZDOCCAT1Text = m_ZDOCCAT1Text;
@synthesize A0S_CUSTOFrom = m_A0S_CUSTOFrom;
@synthesize A0S_CUSTOTo = m_A0S_CUSTOTo;
@synthesize A0S_CUSTOText = m_A0S_CUSTOText;
@synthesize ResultsQuery = m_ResultsQuery;
@synthesize Results = m_Results;

static NSMutableDictionary *aZAPP_ORDER02ParametersLabels = nil;
static SDMODataEntitySchema *aZAPP_ORDER02ParametersEntitySchema = nil;

- (id)init
{
    self = [super init];
    if (self) {
        m_SDMEntry = [BaseEntityType createEmptySDMODataEntryWithSchema:aZAPP_ORDER02ParametersEntitySchema error:nil];
        if (!m_SDMEntry) {
            return nil;
        }        
        m_properties = nil;
        m_baseUrl = nil;
    }
    return self;
}

- (NSMutableDictionary *)getSDMEntriesForNavigationProperties
{
    NSMutableDictionary *dictionary = [NSMutableDictionary dictionary];
    if ([self.Results count] > 0) {
        [dictionary setObject:[self createSDMEntriesForNavigationPropertyEntries:self.Results] forKey:@"Results"];
    }
    return dictionary;
}


- (SDMODataEntry *)buildSDMEntryFromPropertiesAndReturnError:(NSError **)error
{
    if (m_SDMEntry) {
        NSError *innerError = nil;
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.ZDOCCAT1From forSDMPropertyWithName:@"ZDOCCAT1From" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.ZDOCCAT1To forSDMPropertyWithName:@"ZDOCCAT1To" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.ZDOCCAT1Text forSDMPropertyWithName:@"ZDOCCAT1Text" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A0S_CUSTOFrom forSDMPropertyWithName:@"A0S_CUSTOFrom" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A0S_CUSTOTo forSDMPropertyWithName:@"A0S_CUSTOTo" error:&innerError];
    	[BaseODataObject setStringValueForSDMEntry:m_SDMEntry withValue:self.A0S_CUSTOText forSDMPropertyWithName:@"A0S_CUSTOText" error:&innerError];
        [self addRelativeLinksToSDMEntryFromDictionary:[self getSDMEntriesForNavigationProperties]];
        if (innerError) {
            if (error) {
                *error = innerError;
            }
            return nil;
        }
	}
    return m_SDMEntry;
}

+ (void)loadEntitySchema:(SDMODataServiceDocument *)aService
{
    SDMODataCollection *collectionSchema = [aService.schema getCollectionByName:@"AZAPP_ORDER02" workspaceOfCollection:nil];
    aZAPP_ORDER02ParametersEntitySchema = collectionSchema.entitySchema;
}

+ (void)loadLabels:(SDMODataServiceDocument *)aService
{
		NSMutableDictionary *properties = [BaseODataObject getSchemaPropertiesFromCollection:@"AZAPP_ORDER02" andService:aService];
    	if (properties) {    
	    	aZAPP_ORDER02ParametersLabels = [NSMutableDictionary dictionary];
	    	for (SDMODataPropertyInfo *property in [properties allValues]) {
	        	[aZAPP_ORDER02ParametersLabels setValue:property.label forKey:property.name];
	    	}
	    }
	    else {
        	LOGERROR(@"Failed to load SAP labels from service metadata");
    	}
}


+ (NSString *)getLabelForProperty:(NSString *)aPropertyName
{
    return [BaseODataObject getLabelFromDictionary:aZAPP_ORDER02ParametersLabels forProperty:aPropertyName];
}

- (void)loadProperties
{
    [super loadProperties];
	m_ZDOCCAT1From = [self getStringValueForSDMPropertyWithName:@"ZDOCCAT1From"];
	m_ZDOCCAT1To = [self getStringValueForSDMPropertyWithName:@"ZDOCCAT1To"];
	m_ZDOCCAT1Text = [self getStringValueForSDMPropertyWithName:@"ZDOCCAT1Text"];
	m_A0S_CUSTOFrom = [self getStringValueForSDMPropertyWithName:@"A0S_CUSTOFrom"];
	m_A0S_CUSTOTo = [self getStringValueForSDMPropertyWithName:@"A0S_CUSTOTo"];
	m_A0S_CUSTOText = [self getStringValueForSDMPropertyWithName:@"A0S_CUSTOText"];
}

- (void)loadNavigationPropertyQueries
{
    [super loadNavigationPropertyQueries];
    m_ResultsQuery = [self getRelatedLinkForNavigationName:@"Results"];
}

- (void)loadNavigationPropertyData
{
    [super loadNavigationPropertyData];
    
    NSMutableArray *entries = nil;

    entries = [self getInlinedRelatedEntriesForNavigationName:@"Results"];
    m_Results = [AZAPP_ORDER02Result createAZAPP_ORDER02ResultEntriesForSDMEntries:entries];

}

+ (NSMutableArray *)createAZAPP_ORDER02ParametersEntriesForSDMEntries:(NSMutableArray *)sdmEntries
{
    NSMutableArray *entries = [NSMutableArray array];
    for (SDMODataEntry *entry in sdmEntries) {
        AZAPP_ORDER02Parameters *aZAPP_ORDER02ParametersObject = [[AZAPP_ORDER02Parameters alloc] initWithSDMEntry:entry];
        [entries addObject:aZAPP_ORDER02ParametersObject];
    }
    return entries;
}


+ (NSMutableArray *)parseAZAPP_ORDER02ParametersEntriesWithData:(NSData *)aData error:(NSError **)error
{
    NSMutableArray *sdmEntries = [BaseEntityType getSDMEntriesForEntitySchema:aZAPP_ORDER02ParametersEntitySchema andData:aData error:error];
    if (!sdmEntries) {
    	return nil;
    }
	return [AZAPP_ORDER02Parameters createAZAPP_ORDER02ParametersEntriesForSDMEntries:sdmEntries];
}

+ (NSMutableArray *)parseExpandedAZAPP_ORDER02ParametersEntriesWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError **)error
{
    NSMutableArray *sdmEntries = [BaseEntityType getExpandedSDMEntriesForEntitySchema:aZAPP_ORDER02ParametersEntitySchema andData:aData andServiceDocument:aServiceDocument error:error];
    if (!sdmEntries) {
    	return nil;
    }
	return [AZAPP_ORDER02Parameters createAZAPP_ORDER02ParametersEntriesForSDMEntries:sdmEntries];
}

+ (AZAPP_ORDER02Parameters *)parseAZAPP_ORDER02ParametersEntryWithData:(NSData *)aData error:(NSError **)error
{
    NSMutableArray *aZAPP_ORDER02ParametersEntries = [AZAPP_ORDER02Parameters parseAZAPP_ORDER02ParametersEntriesWithData:aData error:error];
    if (!aZAPP_ORDER02ParametersEntries) {
    	return nil;
    }
    return (AZAPP_ORDER02Parameters *)[AZAPP_ORDER02Parameters getFirstObjectFromArray:aZAPP_ORDER02ParametersEntries];
}

+ (AZAPP_ORDER02Parameters *)parseExpandedAZAPP_ORDER02ParametersEntryWithData:(NSData *)aData andServiceDocument:(SDMODataServiceDocument *)aServiceDocument error:(NSError **)error
{
	NSMutableArray *sdmEntries = [BaseEntityType getExpandedSDMEntriesForEntitySchema:aZAPP_ORDER02ParametersEntitySchema andData:aData andServiceDocument:aServiceDocument error:error];
    NSMutableArray *aZAPP_ORDER02ParametersEntries = [AZAPP_ORDER02Parameters createAZAPP_ORDER02ParametersEntriesForSDMEntries:sdmEntries];
	return (AZAPP_ORDER02Parameters *)[AZAPP_ORDER02Parameters getFirstObjectFromArray:aZAPP_ORDER02ParametersEntries];
}


#pragma mark Entity Navigation Property loading methods
- (BOOL)loadResultsWithData:(NSData *)aData error:(NSError **)error
{
    self.Results = [AZAPP_ORDER02Result parseAZAPP_ORDER02ResultEntriesWithData:aData error:error];
    if (!self.Results) {
    	return NO;
    }
    return YES;
}


@end


#pragma mark - ZAPP_ORDER02 Service Proxy


@implementation ZAPP_ORDER02Service

@synthesize AZAPP_ORDER02Query = m_AZAPP_ORDER02Query;
@synthesize AZAPP_ORDER02ResultsQuery = m_AZAPP_ORDER02ResultsQuery;

- (NSString *)getServiceDocumentFilename
{
	return ZAPP_ORDER02_SERVICE_DOCUMENT;
}

- (NSString *)getServiceMetadataFilename
{
	return ZAPP_ORDER02_SERVICE_METADATA;
}

- (void)loadEntitySetQueries
{
	[super loadEntitySetQueries];
    m_AZAPP_ORDER02Query = [self getQueryForRelativePath:@"AZAPP_ORDER02"];
    m_AZAPP_ORDER02ResultsQuery = [self getQueryForRelativePath:@"AZAPP_ORDER02Results"];
}

- (void)loadEntitySchemaForAllEntityTypes
{
    [super loadEntitySchemaForAllEntityTypes];
    [AZAPP_ORDER02Result loadEntitySchema:m_serviceDocument];
    [AZAPP_ORDER02Parameters loadEntitySchema:m_serviceDocument];
}

- (void)loadLabels
{
    [super loadLabels];
    [AZAPP_ORDER02Result loadLabels:m_serviceDocument];
    [AZAPP_ORDER02Parameters loadLabels:m_serviceDocument];
}

 
#pragma mark Service Entity Set methods
- (NSMutableArray *)getAZAPP_ORDER02WithData:(NSData *)aData error:(NSError **)error
{
	return [AZAPP_ORDER02Parameters parseExpandedAZAPP_ORDER02ParametersEntriesWithData:aData andServiceDocument:self.sdmServiceDocument error:error];
}

- (ODataQuery *)getAZAPP_ORDER02EntryQueryWithZDOCCAT1From:(NSString *)ZDOCCAT1From andZDOCCAT1To:(NSString *)ZDOCCAT1To andA0S_CUSTOFrom:(NSString *)A0S_CUSTOFrom andA0S_CUSTOTo:(NSString *)A0S_CUSTOTo
{
	ZDOCCAT1From = [ODataQuery encodeURLParameter:ZDOCCAT1From];
	ZDOCCAT1To = [ODataQuery encodeURLParameter:ZDOCCAT1To];
	A0S_CUSTOFrom = [ODataQuery encodeURLParameter:A0S_CUSTOFrom];
	A0S_CUSTOTo = [ODataQuery encodeURLParameter:A0S_CUSTOTo];
	NSString *relativePath = [NSString stringWithFormat:@"AZAPP_ORDER02(ZDOCCAT1From=%@,ZDOCCAT1To=%@,A0S_CUSTOFrom=%@,A0S_CUSTOTo=%@)", ZDOCCAT1From, ZDOCCAT1To, A0S_CUSTOFrom, A0S_CUSTOTo];
	ODataQuery *query = [self getQueryForRelativePath:relativePath];
	return query;
}

- (ODataQuery *)getAZAPP_ORDER02EntryQueryTypedWithZDOCCAT1From:(NSString *)ZDOCCAT1From andZDOCCAT1To:(NSString *)ZDOCCAT1To andA0S_CUSTOFrom:(NSString *)A0S_CUSTOFrom andA0S_CUSTOTo:(NSString *)A0S_CUSTOTo
{
	id <URITypeConverting> converter = [ODataURITypeConverter uniqueInstance];
	NSString *ZDOCCAT1FromUri = [ODataQuery encodeURLParameter:[converter convertToEdmStringURI:ZDOCCAT1From]];
	NSString *ZDOCCAT1ToUri = [ODataQuery encodeURLParameter:[converter convertToEdmStringURI:ZDOCCAT1To]];
	NSString *A0S_CUSTOFromUri = [ODataQuery encodeURLParameter:[converter convertToEdmStringURI:A0S_CUSTOFrom]];
	NSString *A0S_CUSTOToUri = [ODataQuery encodeURLParameter:[converter convertToEdmStringURI:A0S_CUSTOTo]];
	NSString *relativePath = [NSString stringWithFormat:@"AZAPP_ORDER02(ZDOCCAT1From=%@,ZDOCCAT1To=%@,A0S_CUSTOFrom=%@,A0S_CUSTOTo=%@)", ZDOCCAT1FromUri, ZDOCCAT1ToUri, A0S_CUSTOFromUri, A0S_CUSTOToUri];
	ODataQuery *query = [self getQueryForRelativePath:relativePath];
	return query;
}

- (AZAPP_ORDER02Parameters *)getAZAPP_ORDER02EntryWithData:(NSData *)aData error:(NSError **)error
{
	return [AZAPP_ORDER02Parameters parseExpandedAZAPP_ORDER02ParametersEntryWithData:aData andServiceDocument:self.sdmServiceDocument error:error];
}

- (NSMutableArray *)getAZAPP_ORDER02ResultsWithData:(NSData *)aData error:(NSError **)error
{
	return [AZAPP_ORDER02Result parseExpandedAZAPP_ORDER02ResultEntriesWithData:aData andServiceDocument:self.sdmServiceDocument error:error];
}

- (ODataQuery *)getAZAPP_ORDER02ResultsEntryQueryWithROWID:(NSString *)ROWID
{
	ROWID = [ODataQuery encodeURLParameter:ROWID];
	NSString *relativePath = [NSString stringWithFormat:@"AZAPP_ORDER02Results(ROWID=%@)", ROWID];
	ODataQuery *query = [self getQueryForRelativePath:relativePath];
	return query;
}

- (ODataQuery *)getAZAPP_ORDER02ResultsEntryQueryTypedWithROWID:(NSString *)ROWID
{
	id <URITypeConverting> converter = [ODataURITypeConverter uniqueInstance];
	NSString *ROWIDUri = [ODataQuery encodeURLParameter:[converter convertToEdmStringURI:ROWID]];
	NSString *relativePath = [NSString stringWithFormat:@"AZAPP_ORDER02Results(ROWID=%@)", ROWIDUri];
	ODataQuery *query = [self getQueryForRelativePath:relativePath];
	return query;
}

- (AZAPP_ORDER02Result *)getAZAPP_ORDER02ResultsEntryWithData:(NSData *)aData error:(NSError **)error
{
	return [AZAPP_ORDER02Result parseExpandedAZAPP_ORDER02ResultEntryWithData:aData andServiceDocument:self.sdmServiceDocument error:error];
}



#pragma mark Service Function Import methods 

@end
