/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.300.0
  
 File: BaseODataObject.m
 Abstract: The base class for all OData classes which represent OData types.
 
 
 */


#import "BaseODataObject.h"

// SAP OData Mobile SDK Imports
#import "SDMODataEntitySchema.h"
#import "SDMODataCollection.h"
#import "Logger.h"
#import "ErrorHandling.h"

@implementation BaseODataObject

+ (NSMutableDictionary *)getSchemaPropertiesFromCollection:(NSString *)aCollectionName andService:(SDMODataServiceDocument *)aSDMServiceDocument
{
    SDMODataSchema *schema = aSDMServiceDocument.schema;
    SDMODataCollection *entityCollection = [schema getCollectionByName:aCollectionName];
    if (!entityCollection) {
    	NSString *localizedMessage = NSLocalizedString(@"Collection %@ not found in the service metadata", @"Collection %@ not found in the service metadata");
        NSString *errorMessage = [NSString stringWithFormat:localizedMessage, aCollectionName];
        LOGERROR(errorMessage);
        return nil;
    }
	return entityCollection.entitySchema.root.children;
}

+ (NSString *)getLabelFromDictionary:(NSMutableDictionary *)aLabelDictionary forProperty:(NSString *)aPropertyName
{
    NSString *propertyLabel = nil;
    if (aLabelDictionary) {
        propertyLabel = [aLabelDictionary valueForKey:aPropertyName];
        if ((![propertyLabel isKindOfClass:[NSString class]]) || ([propertyLabel length] == 0)) { //Label was not found for property
            propertyLabel = aPropertyName; //Return the property name if the label is not defined
        }
    }
    else {
        LOGWARNING(@"Labels dictionary was not initialized. Call the loadLabels method of the appropriate entity class");   
    }
    return propertyLabel;
}

+ (BOOL)setStringValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSString *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueString *property = (SDMODataPropertyValueString *)[aSDMEntry getPropertyValueByPath:aName];
        [property setValue:aValue];
    }
    @catch (NSException* e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);        
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setDateTimeValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSDate *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueDateTime *property = (SDMODataPropertyValueDateTime *)[aSDMEntry getPropertyValueByPath:aName];
        [property setDateValue:aValue];
    }
    @catch (NSException* e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setDecimalValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSDecimalNumber *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueDecimal *property = (SDMODataPropertyValueDecimal *)[aSDMEntry getPropertyValueByPath:aName];
        [property setDecimalValue:aValue];
    }
    @catch (NSException *e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setIntValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSNumber *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueInt *property = (SDMODataPropertyValueInt *)[aSDMEntry getPropertyValueByPath:aName];
        [property setIntValue:aValue];
    }
    @catch (NSException *e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setBooleanValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSNumber *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueBoolean *property = (SDMODataPropertyValueBoolean *)[aSDMEntry getPropertyValueByPath:aName];
        [property setBooleanValue:aValue];
    }
    @catch (NSException *e) {
        result = NO;
        NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setSingleValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSNumber *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueSingle *property = (SDMODataPropertyValueSingle *)[aSDMEntry getPropertyValueByPath:aName];
        [property setSingleValue:aValue];
    }
    @catch (NSException *e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setDoubleValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSNumber *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueDouble *property = (SDMODataPropertyValueDouble *)[aSDMEntry getPropertyValueByPath:aName];
        [property setDoubleValue:aValue];
    }
    @catch (NSException *e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setGuidValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSString *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueGuid *property = (SDMODataPropertyValueGuid *)[aSDMEntry getPropertyValueByPath:aName];
        [property setValue:aValue];
    }
    @catch (NSException *e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setDateTimeOffsetValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSString *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueDateTimeOffset *property = (SDMODataPropertyValueDateTimeOffset *)[aSDMEntry getPropertyValueByPath:aName];
        [property setValue:aValue];
    }
    @catch (NSException *e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setBinaryValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(NSMutableData *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueBinary *property = (SDMODataPropertyValueBinary *)[aSDMEntry getPropertyValueByPath:aName];
        [property setBinaryData:aValue];
    }
    @catch (NSException *e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}

+ (BOOL)setTimeValueForSDMEntry:(SDMODataEntry *)aSDMEntry withValue:(SDMDuration *)aValue forSDMPropertyWithName:(NSString *)aName error:(NSError * __autoreleasing *)error
{
	BOOL result = YES;
    @try {
        SDMODataPropertyValueTime *property = (SDMODataPropertyValueTime *)[aSDMEntry getPropertyValueByPath:aName];
        [property setTimeValue:aValue];
    }
    @catch (NSException *e) {
    	result = NO;
    	NSString *localizedMessage = NSLocalizedString(@"Exception during setting value %@ to property %@. Exception: %@", @"Exception during setting value %@ to property %@. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aValue, aName, e.description];
        LOGERROR(exceptionMsg);
        if (error) {
            *error = [[NSError alloc] initWithDomain:ERROR_DOMAIN code:SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE userInfo:[NSDictionary dictionaryWithObject:exceptionMsg forKey:NSLocalizedDescriptionKey]];
        }
    }
    return result;
}


- (id)initWithSDMDictionary:(NSDictionary *)aDictionary
{
    if (self = [super init]) {
        m_properties = [NSDictionary dictionaryWithDictionary:aDictionary];
        [self loadProperties];
    }
    return self;
}

- (NSDictionary *)getDictionaryForComplexTypeProperty:(NSString *)aPropertyName
{
    SDMODataPropertyValueComplex *complexProperty = (SDMODataPropertyValueComplex *)[self getValueForProperty:aPropertyName];
    return complexProperty.children;
}

- (SDMODataPropertyValueObject *)getValueForProperty:(NSString *)aPropertyName
{
    return [m_properties objectForKey:aPropertyName];
}


- (NSString *)getStringValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSString *result = nil;
    @try {
        SDMODataPropertyValueString *SDMValue = (SDMODataPropertyValueString *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (NSDate *)getDateTimeValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSDate *result = nil;
    @try {
        SDMODataPropertyValueDateTime *SDMValue = (SDMODataPropertyValueDateTime *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getDateValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (NSDecimalNumber *)getDecimalValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSDecimalNumber *result = nil;
    @try {
        SDMODataPropertyValueDecimal *SDMValue = (SDMODataPropertyValueDecimal *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getDecimalValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (NSNumber *)getIntValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSNumber *result = nil;
    @try {
        SDMODataPropertyValueInt *SDMValue = (SDMODataPropertyValueInt *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getIntValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (NSNumber *)getBooleanValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSNumber *result = nil;
    @try {
        SDMODataPropertyValueBoolean *SDMValue = (SDMODataPropertyValueBoolean *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getBooleanValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (NSNumber *)getSingleValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSNumber *result = nil;
    @try {
        SDMODataPropertyValueSingle *SDMValue = (SDMODataPropertyValueSingle *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getSingleValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (NSNumber *)getDoubleValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSNumber *result = nil;
    @try {
        SDMODataPropertyValueDouble *SDMValue = (SDMODataPropertyValueDouble *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getDoubleValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (NSString *)getGuidValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSString *result = nil;
    @try {
        SDMODataPropertyValueGuid *SDMValue = (SDMODataPropertyValueGuid *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
    
}

- (NSString *)getDateTimeOffsetValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSString *result = nil;
    @try {
        SDMODataPropertyValueDateTimeOffset *SDMValue = (SDMODataPropertyValueDateTimeOffset *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (NSMutableData *)getBinaryValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    NSMutableData *result = nil;
    @try {
        SDMODataPropertyValueBinary *SDMValue = (SDMODataPropertyValueBinary *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getBinaryData];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (SDMDuration *)getTimeValueForSDMPropertyWithName:(NSString *)aPropertyName
{
    SDMDuration *result = nil;
    @try {
        SDMODataPropertyValueTime *SDMValue = (SDMODataPropertyValueTime *)[self getValueForProperty:aPropertyName];
        result = [SDMValue getTimeValue];
    }
    @catch (NSException *e) {
    	NSString *localizedMessage = NSLocalizedString(@"Exception during parsing property '%@'. Exception: %@", @"Exception during parsing property '%@'. Exception: %@");
        NSString *exceptionMsg = [NSString stringWithFormat:localizedMessage, aPropertyName, e.description];
        LOGERROR(exceptionMsg);
    }
    return result;
}

- (void)loadProperties
{
	
}

@end
