/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.300.0
 
 File: BaseComplexType.m
 Abstract: The base class for all OData complex types. Inherits from BaseODataObject.
 
 
 */

#import "BaseComplexType.h"

@implementation BaseComplexType 

- (BOOL)setComplexTypePropertiesToSDMEntry:(SDMODataEntry *)aSDMEntry complexTypePropertyName:(NSString *)aComplexPropertyName error:(NSError *__autoreleasing *)error
{
    return YES;
}
@end
