/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.300.0
  
 File: CSRFData.h
 Abstract: Holds the CSRF data (cookie and token).
 
 
 */

#import "CSRFData.h"

@implementation CSRFData
@synthesize token;
@synthesize cookie;
@synthesize cookies;

@end
