/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.300.0
  
 File: ErrorHandling.h
 Abstract: Contains constants used for error handling.
 
 
*/


#import <Foundation/Foundation.h>

#define ERROR_DOMAIN @"SAP Netweaver Gateway Service Proxy"
#define SCHEMA_ERROR_CODE 1001
#define RESPONSE_PARSER_ERROR_CODE 1002
#define SDM_ENTRY_INVALID_ERROR_CODE 1003
#define SDM_ENTRY_PROPERTY_VALUE_ERROR_CODE 1004
#define SDM_ENTRY_XML_BUILDER_ERROR_CODE 1005