/*
 
 Auto-Generated by the SAP NetWeaver Gateway developer tool for Xcode, Version 2.5.300.0
  
 File: Logger.m
 Abstract: Logger class.
 
 
*/


#import "Logger.h"
#import "SDMLogger.h"


@implementation Logger


+ (void)logError:(NSString *)msg withInfo:(NSString *)info
{
    NSLog(@"ERROR: %@ %@", msg, info);
}

+ (void)logWarning:(NSString *)msg withInfo:(NSString *)info
{
    NSLog(@"WARNING: %@ %@", msg, info);
}

+ (void)logNotice:(NSString *)msg withInfo:(NSString *)info
{
    NSLog(@"NOTICE: %@ %@", msg, info);
}

+ (void)logError:(NSString *)msg
{
    [Logger logError:msg withInfo:@""];
}

+ (void)logWarning:(NSString *)msg
{
    [Logger logWarning:msg withInfo:@""];
}

+ (void)logNotice:(NSString *)msg
{
    [Logger logNotice:msg withInfo:@""];
}

+ (void)enableSDMDetailedLogging
{
    [SDMLogger enableLogging];
}

+ (void)disableSDMDetailedLogging
{
    [SDMLogger disableLogging];
}

@end
